# Generated by Django 3.2.2 on 2021-05-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('blood_group', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=10)),
                ('decease', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
    ]
