# Generated by Django 3.2.2 on 2021-05-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
