# Generated by Django 3.2.2 on 2021-05-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_app', '0003_bank_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='status',
            field=models.CharField(default='Active', max_length=10),
        ),
    ]
