# Generated by Django 3.2.2 on 2021-05-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_app', '0004_bank_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
