# Generated by Django 3.2.2 on 2021-05-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_app', '0006_chat_chatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='req_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
